# Generated by Django 5.1.7 on 2025-03-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('moeda', models.CharField(max_length=3)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
